

name: "pornhub.com"

on:
  workflow_dispatch:  # با کلیک دستی اجرا میشه
    inputs:
      video_url:
        description: 'لینک فیلم از سایت خودم'
        required: true
        type: string

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: نصب yt-dlp
        run: |
          pip install yt-dlp
         
      - name: دانلود فیلم
        run: |
          yt-dlp "${{ github.event.inputs.video_url }}"
         
      - name: آماده کردن فایل برای آپلود
        run: |
          mkdir output
          mv *.mp4 *.mkv *.webm output/ 2>/dev/null || true
         
      - name: ذخیره فایل دانلود شده
        uses: actions/upload-artifact@v4
        with:
          name: my-video
          path: output/
